controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

quiz:
    resource: '../src/Controller/Quiz'
    type: attribute

question:
    resource: '../src/Controller/Question'
    type: attribute